spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://${DB_URL}:3306/profileservice
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
    show-sql: false
