spring:
  profiles:
    active: prod
  config:
    import: aws-parameterstore:/profile-service-app/prod/

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true

info:
  app:
    name: ${TEAM_NAME}
    version: 1.0.0

logging:
  level:
    root: info
